[project]
name = "tradebot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "kiteconnect>=5.0.1",
    "polars>=1.36.1",
    "pyotp>=2.9.0",
    "ratelimit>=2.2.1",
    "selenium>=4.39.0",
]
